### PR TITLE
Modified the code of AzureStorageBlobDataCopyTool (12) ( Added create tables scripts. ) 

### PR DESCRIPTION
**Pull request by daisukenishino**
- Added create tables scripts.
- Corresponding to the following correction.  
https://github.com/OpenTouryoProject/OpenTouryo/pull/111

### CODE REVIEW

**Comment by yusukemaegawa** [comment]
The compilation of this program fails.
(The touryo dll(s) and azure dll(s) cannot be found.)

If environmental construction is necessary, please describe the way.

**Comment by SandeepNayak077** [comment]
@yusukemaegawa 
\>> The compilation of this program fails.
\>> (The touryo dll(s) and azure dll(s) cannot be found.)

\<Our Idea>
If OpenTouryo and CloudOS projects are placed in the same location.
For Example, we have placed both projects in 'C' drive: 
- C:\CloudOS\\..
- C:\OpenTouryo\\..

Then, the touryo DLL(s) can be referenced as follows:
- ..\\..\\..\\..\\OpenTouryo\root\programs\C#\Frameworks\Infrastructure\Build\

However, azure dll(s) are not used in OpenTouryo project,
We need a location to place the azure dll(s) in the CloudOs project.

We think Dll can be placed in the follwing location:
- \CloudOS\programs\Public\Dll\azure dll(s)

Please review and suggest us.

**Comment by daisukenishino** [comment]
@SandeepNayak077

This fix will be responded by @daisukenishino.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Ok. Thank you.

**Pull request closed without merging**
